.TH "data_input_objects.ETESim_Input" 3 "Thu May 21 2020" "ETESim Plotting GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_input_objects.ETESim_Input
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, inpDir)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ETESim Plotting GUI from the source code\&.
