.TH "etesim_pp_gui.SimpleGUI" 3 "Thu May 21 2020" "ETESim Plotting GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
etesim_pp_gui.SimpleGUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits Tk\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, *args, **kwargs)"
.br
.ti -1c
.RI "None \fBbuildTabs\fP (self, ttk\&.Notebook parent)"
.br
.ti -1c
.RI "None \fBwaitToPlot\fP (self, event=None)"
.br
.RI "Utility functions\&. "
.ti -1c
.RI "None \fBautosizer\fP (self, tabs, event=None)"
.br
.ti -1c
.RI "pd\&.DataFrame \fBassetPlotDF\fP (self, bool showAllRuns, int specialRun)"
.br
.RI "Plotting functions\&. "
.ti -1c
.RI "pd\&.DataFrame \fBmissilePlotDF\fP (self)"
.br
.ti -1c
.RI "None \fBstartPlot\fP (self, event=None, item=None, mode=None)"
.br
.ti -1c
.RI "None \fBstartMatPlot\fP (self, float startTime, event=None, item=None, mode=None)"
.br
.ti -1c
.RI "None \fBfinishMatPlot\fP (self, float startTime)"
.br
.ti -1c
.RI "tuple \fBplotOptions\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBplotCols\fP"
.br
.ti -1c
.RI "\fBdimensions\fP"
.br
.ti -1c
.RI "\fBx\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.ti -1c
.RI "\fBz\fP"
.br
.ti -1c
.RI "\fBmissileDF\fP"
.br
.ti -1c
.RI "\fBassets\fP"
.br
.ti -1c
.RI "\fBtoolbar\fP"
.br
.ti -1c
.RI "\fBfigure\fP"
.br
.ti -1c
.RI "\fBcanvas\fP"
.br
.ti -1c
.RI "\fBcursor\fP"
.br
.ti -1c
.RI "\fBtitleColorRGB\fP"
.br
.ti -1c
.RI "\fBtitleColorHex\fP"
.br
.ti -1c
.RI "\fBplotColorRGB\fP"
.br
.ti -1c
.RI "\fBplotColorHex\fP"
.br
.ti -1c
.RI "\fBavailableRuns\fP"
.br
.ti -1c
.RI "\fBshowCursor\fP"
.br
.ti -1c
.RI "\fBplotEngine\fP"
.br
.ti -1c
.RI "\fBtabs\fP"
.br
.ti -1c
.RI "\fBstatusBar\fP"
.br
.ti -1c
.RI "\fBstatus\fP"
.br
.ti -1c
.RI "\fBplotProgress\fP"
.br
.ti -1c
.RI "\fBplotProgressFrame\fP"
.br
.ti -1c
.RI "\fBplotProgressLbl\fP"
.br
.ti -1c
.RI "\fBplotProgressText\fP"
.br
.ti -1c
.RI "\fBplotProgressBar\fP"
.br
.ti -1c
.RI "\fBxkcdMode\fP"
.br
.ti -1c
.RI "\fBxkcdModeCB\fP"
.br
.ti -1c
.RI "\fBinpIcon\fP"
.br
.ti -1c
.RI "\fBviewIcon\fP"
.br
.ti -1c
.RI "\fBviewPane\fP"
.br
.ti -1c
.RI "\fBautoColors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A subclass of tk.Tk which will serve as the main driver for the GUI.
This GUI is intended to plot various input data from simulations,
currently (almost) working with ETESim.

Parameters
----------
*args : standard argument list for a tk.Tk instance

**kwargs : keyword argument list for tk.Tk instance

Returns
-------
None
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def etesim_pp_gui\&.SimpleGUI\&.__init__ ( self, * args, ** kwargs)"

.PP
.nf
The constructor function for the GUI

Parameters
----------
*args : standard argument list for a tk.Tk instance

**kwargs : keyword argument list for tk.Tk instance

Returns
-------
None
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " pd\&.DataFrame etesim_pp_gui\&.SimpleGUI\&.assetPlotDF ( self, bool showAllRuns, int specialRun)"

.PP
Plotting functions\&. 
.PP
.nf
The DataFrame used to plot fixed assets on top of trajectories.

Parameters
----------
showAllRuns : bool
    A flag for whether only select trajectories are being displayed
specialRun : int
    The run of interest in case showAllRuns is false

Returns
-------
Pandas DataFrame
    An index of information containing metadata and location data for
    the assets we intend to plot.
.fi
.PP
 
.SS " None etesim_pp_gui\&.SimpleGUI\&.autosizer ( self,  tabs,  event = \fCNone\fP)"

.PP
.nf
Adjusts the tkinter Notebook (tabbed) section size automatically.

Parameters
----------
event : tkinter.Event, optional
    A parameter to catch any trace passes. The default is None.

Returns
-------
None
.fi
.PP
 
.SS " None etesim_pp_gui\&.SimpleGUI\&.buildTabs ( self, ttk\&.Notebook parent)"

.PP
.nf
An obscenely large and not very well-organized layout
for the tabs inside a tkinter Notebook. Is essentially a giant main().

Parameters
----------
parent : ttk.Notebook
    A tkinter object that can have tabs applied to it.

Returns
-------
None
.fi
.PP
 
.SS " None etesim_pp_gui\&.SimpleGUI\&.finishMatPlot ( self, float startTime)"

.PP
.nf
Generates a new plot on the figure set up in startPlot.

Parameters
----------
startTime : float
    The time plotting began. Used to update the user on total
    rendering time.

Returns
-------
None
.fi
.PP
 
.SS " pd\&.DataFrame etesim_pp_gui\&.SimpleGUI\&.missilePlotDF ( self)"

.PP
.nf
Generates a smaller dataframe for plotting from the massive
one stored in memory

Returns
-------
plotDF : pd.DataFrame
    A 2 or 3 column Pandas DataFrame containing the x, y, and
    sometimes z data for plotting
.fi
.PP
 
.SS " tuple etesim_pp_gui\&.SimpleGUI\&.plotOptions ( self)"

.PP
.nf
A shorthand for aggregating all the different plot options
the user can specify

Returns
-------
plotStyle : str
    Choices are "line" or "scatter"
showAllRuns : bool
    Whether to display all runs at once or only certain ones
transparentRuns : bool
    Whether, when showAllRuns is False, to display the other runs
    faded out
specialRun : int
    The user-specified run to analyze
autoColor : bool
    Whether the trajectories should be colored automatically
plotColor : str
    A user-specified color for trajectories
dimensions : int
    Choices are 2 or 3
lineStyle : str
    Options for different line styles. (Full, dashed, etc.)
scatterStyle : str
    Options for different scatter plot markers.
colors : str
    The colors to use if autoColor is set to True
.fi
.PP
 
.SS " None etesim_pp_gui\&.SimpleGUI\&.startMatPlot ( self, float startTime,  event = \fCNone\fP,  item = \fCNone\fP,  mode = \fCNone\fP)"

.PP
.nf
Sets up initial pieces for plotting with matplotlib.

Parameters
----------
startTime : float
    The time (in seconds) before the plot process beings
event : int or tkinter.Event, optional
    Often called as a 1 instead of tk.Event.
    If not None, indicates that the plot should update
    The default is None.
item : tkinter.Event, optional
    Only passed when using a trace.
    (tkinter Events are passed as triples.)
    The default is None.
mode : tkinter.Event, optional
    Only passed when using a trace.
    (tkinter Events are passed as triples.)
    The default is None.

Returns
-------
None
.fi
.PP
 
.SS " None etesim_pp_gui\&.SimpleGUI\&.startPlot ( self,  event = \fCNone\fP,  item = \fCNone\fP,  mode = \fCNone\fP)"

.PP
.nf
Sets up all the variables and options necessary to generate
a plot in the viewer pane.

Parameters
----------
event : int or tkinter.Event, optional
    Often called as a 1 instead of tk.Event.
    If not None, indicates that the plot should update
    The default is None.
item : tkinter.Event, optional
    Only passed when using a trace.
    (tkinter Events are passed as triples.)
    The default is None.
mode : tkinter.Event, optional
    Only passed when using a trace.
    (tkinter Events are passed as triples.)
    The default is None.

Returns
-------
None
.fi
.PP
 
.SS " None etesim_pp_gui\&.SimpleGUI\&.waitToPlot ( self,  event = \fCNone\fP)"

.PP
Utility functions\&. 
.PP
.nf
Creates a queue to wait for an event to finish. This allows users
to enter multiple keystrokes or perform other actions before the
GUI automatically updates.

A particular usage is in letting users enter a title without the
GUI trying to update the graph after after each letter.

Parameters
----------
event : tkinter.Event, optional
    The event being potentially held. The default is None.

Returns
-------
None
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for ETESim Plotting GUI from the source code\&.
